### PR TITLE
Bug 440. Make the RSE protocols table background darker

### LINKED ISSUE #440: Change the background of the RSE protocols table header
### Description

The backgrounds of last few columns headers seem too light and clash with the white text.
image

### Motivation

Improve readability and accessibility of the page.

### Change

Make either the background or text color darker.

### Additional Information

- [ ] The Rucio API needs to be changed.

### PR DESCRIPTION
**Pull request by MytsV**
Fix #440

### CODE REVIEW

**Comment by maany** [comment]
Could you pick the color from the theme we have defined in `tailwind.config.js` instead?

File: src/component-library/Pages/RSE/PageRSEProtocols.tsx [hunk 1]
```diff
@@ -17,8 +17,8 @@ export const PageRSEProtocols = (
     }
 ) => {
     const shortstyle = { style: "w-20" }
-    const shortstyleblue = { style: "w-20 bg-blue-100"}
-    const shortstylepink = { style: "w-20 bg-pink-100"}
+    const shortstyleblue = { style: "w-20 bg-blue-500"}
```
Comment (maany) [inline src/component-library/Pages/RSE/PageRSEProtocols.tsx:20]: Take a look at the theme in tailwind.config.js. Let's use the colors defined there over the one's that come one the default tailwind theme. Let me know if this turns everything into a huge refactor. In which case, I will accept the PR as it is. ;)

**Review by maany — DISMISSED** [review]

**Comment by MytsV** [comment]
> Could you pick the color from the theme we have defined in `tailwind.config.js` instead?

Done! I chose the closest colors from the config. I don't currently want to refactor this code as the replacement by AG Grid is probable.

**Review by maany — APPROVED** [review]
