### PR TITLE
Keyboard navigation, accessibility, miscellaneous fixes

### LINKED ISSUE #62: Add Keyboard Navigation/Survey for accessibility
### Description

The Login Page needs to be keyboard compliant (login on enter keypress) and must also be tab-able, with focus on the first entry prompt.

### Motivation

Websites need to be keyboard navigable and a11y compliant as per latest standards to enable interactions via other means.

### Change

Survey the login page with some accessibility tools, test for keyboard nav compatibility.

### PR DESCRIPTION
**Pull request by nimishbongale**
Fixes #62 

- Adds tabbing between input fields
- Fixes some accessibility issues
- Triggers form submit on enter keypress
- Replaces some occurrences of 'any' with 'unknown'

### CODE REVIEW

**Review by maany — APPROVED** [review]

**Comment by maany** [comment]
@nimishbongale can you resolve the merge conflict, thanks :)

File: src/components/Login.tsx [hunk 1]
```diff
@@ -105,77 +105,91 @@ function Login() {
...
+                } else {
                     showAlert({
-                        message: 'Invalid credentials',
+                        message: 'Unable to fetch response from server.',
                         variant: 'error',
                     })
-                } else {
-                    throw new Error('Login failed')
                 }
                 return response
```
Comment (maany) [inline src/components/Login.tsx:190]: this can be removed ;)

File: src/stories/Page/Page.tsx [hunk 2]
```diff
@@ -11,7 +11,7 @@ type User = {
     children?: any
 }
 
-export const Page: React.VFC = (children: any) => {
+export const Page: React.VFC = () => {
```
Comment (maany) [inline src/stories/Page/Page.tsx:14]: Looks like React.VFC is deprecated ;) Any chance we can get rid of VFC/FC altogether?

File: src/components/Login.tsx (hunk 1 above)
Comment (nimishbongale) [reply src/components/Login.tsx:190]: Sure!

File: src/stories/Page/Page.tsx (hunk 2 above)
Comment (nimishbongale) [reply src/stories/Page/Page.tsx:14]: Yes, can take measures as pointed out in this article:

https://www.mydatahack.com/moving-away-from-fc-and-vfc/

File: src/components/Login.tsx (hunk 1 above)
Comment (maany) [reply src/components/Login.tsx:190]: Hey @nimishbongale, I meant we should remove `return response`. In case of an error, we would return `undefined` from this block, which would not be handled by this function. Would you agree that we should handle the expectations here or throw a well-defined expectation from the restApiWrapper functions?

Comment (nimishbongale) [reply src/components/Login.tsx:190]: Ah! Alright! Makes sense. Will do the needful 😄

**Review by maany — APPROVED** [review]
