### PR TITLE
Fix redirect authenticated users to dashboard 

### LINKED ISSUE #405: Fix redirect authenticated users
### Description

 After a user successfully logs in, the application redirects them to a specific page (src/app/page.tsx) instead of the default dashboard (/dashboard).

### Steps to reproduce

_No response_

### Rucio WebUI Version

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by esilvaju**
Fixes #405

### CODE REVIEW

File: src/app/page.tsx [hunk 1]
```diff
@@ -1,91 +1,5 @@
-import Image from 'next/image'
-import { Inter } from '@next/font/google'
-import styles from './page.module.css'
-import Link from 'next/link';
-
-const inter = Inter({ subsets: ['latin'] })
+import { redirect, RedirectType } from 'next/navigation';
```
Comment (maany) [inline src/app/page.tsx:1]: RedirectType is an unused import

**Review by maany — CHANGES_REQUESTED** [review]

File: src/app/page.tsx (hunk 1 above)
Comment (esilvaju) [reply src/app/page.tsx]: Done !

**Review by maany — APPROVED** [review]
